import Foundation

struct DiagnosticData {
    let systemInfo: String
    let pluginStatus: String
    let crashLogs: String
    let auValidation: String
    let userFeedback: String
    let pulpModelState: String
    let securityInfo: String
    let crashFilePaths: [String]
    let pulpModelStatePath: String?
}

/// Strip the local username, home path, and hostname from a diagnostic report
/// so it can be shared without leaking PII. Mirrors the JUCE (Windows/Linux)
/// implementation so both platforms honor ANONYMIZE_USERNAMES / EXCLUDE_USER_PATHS.
/// No-op unless `enabled`.
func anonymizeDiagnosticText(_ text: String, enabled: Bool) -> String {
    guard enabled else { return text }
    var result = text
    let home = FileManager.default.homeDirectoryForCurrentUser.path  // /Users/<name>
    let username = NSUserName()
    if !home.isEmpty { result = result.replacingOccurrences(of: home, with: "/Users/<user>") }
    if !username.isEmpty {
        result = result.replacingOccurrences(of: "/Users/\(username)", with: "/Users/<user>")
        result = result.replacingOccurrences(of: "/\(username)/", with: "/<user>/")
    }
    let hostname = ProcessInfo.processInfo.hostName
    if !hostname.isEmpty { result = result.replacingOccurrences(of: hostname, with: "<hostname>") }
    return result
}

func renderDiagnosticReport(_ data: DiagnosticData, appName: String, appVersion: String) -> String {
    var body = ""

    if !data.userFeedback.isEmpty {
        body += "## User Feedback\n\n"
        body += data.userFeedback
        body += "\n\n---\n\n"
    }

    body += data.systemInfo
    body += "\n\n---\n\n"
    body += data.pluginStatus
    body += "\n\n---\n\n"
    body += data.securityInfo
    body += "\n\n---\n\n"
    body += data.pulpModelState
    body += "\n\n---\n\n"
    body += data.crashLogs
    body += "\n\n---\n\n"
    body += data.auValidation
    body += "\n\n---\n\n"
    body += "_Report generated by \(appName) v\(appVersion)_\n"

    return body
}

class DiagnosticCollector {
    private let config: AppConfig
    private let fileManager = FileManager.default

    init(config: AppConfig) {
        self.config = config
    }

    func collectDiagnostics(userFeedback: String = "") async -> DiagnosticData {
        async let systemInfo = collectSystemInfo()
        async let plugin = collectPluginStatus()
        async let crashes = collectCrashLogs()
        async let auValidation = runAUValidation()
        async let pulpModel = collectPulpModelState()

        let pluginResult = await plugin
        let crashResult = await crashes
        let pulpModelResult = await pulpModel

        return await DiagnosticData(
            systemInfo: systemInfo,
            pluginStatus: pluginResult.status,
            crashLogs: crashResult.logs,
            auValidation: auValidation,
            userFeedback: userFeedback,
            pulpModelState: pulpModelResult.summary,
            securityInfo: pluginResult.security,
            crashFilePaths: crashResult.paths,
            pulpModelStatePath: pulpModelResult.modelStatePath
        )
    }

    private func collectSystemInfo() async -> String {
        var info = "# System Information\n\n"

        let osVersion = ProcessInfo.processInfo.operatingSystemVersionString
        info += "**macOS Version:** \(osVersion)\n"

        if let modelName = getSystemProfilerInfo("SPHardwareDataType", key: "Model Name") {
            info += "**Model:** \(modelName)\n"
        }

        if let chipType = getSystemProfilerInfo("SPHardwareDataType", key: "Chip") {
            info += "**Chip:** \(chipType)\n"
        } else if let processorName = getSystemProfilerInfo("SPHardwareDataType", key: "Processor Name") {
            info += "**Processor:** \(processorName)\n"
        }

        if let memory = getSystemProfilerInfo("SPHardwareDataType", key: "Memory") {
            info += "**Memory:** \(memory)\n"
        }

        info += "\n## Audio Devices\n\n"
        if let audioDevices = listAudioDevices() {
            info += audioDevices
        } else {
            info += "_Could not retrieve audio device list_\n"
        }

        return info
    }

    private func collectPluginStatus() async -> (status: String, security: String) {
        var status = "# Plugin Status\n\n"
        var security = "# Security Information\n\n"
        var foundAnySecurityInfo = false

        if config.checkAU {
            let result = scanPluginFormat(
                label: "Audio Unit",
                subdirectory: "Components",
                extensionName: "component"
            )
            status += result.status
            security += result.security
            foundAnySecurityInfo = foundAnySecurityInfo || result.found
        }

        if config.checkVST3 {
            let result = scanPluginFormat(
                label: "VST3",
                subdirectory: "VST3",
                extensionName: "vst3"
            )
            status += result.status
            security += result.security
            foundAnySecurityInfo = foundAnySecurityInfo || result.found
        }

        if config.checkCLAP {
            let result = scanPluginFormat(
                label: "CLAP",
                subdirectory: "CLAP",
                extensionName: "clap"
            )
            status += result.status
            security += result.security
            foundAnySecurityInfo = foundAnySecurityInfo || result.found
        }

        if config.checkStandalone {
            let standalonePaths = [
                "/Applications/\(config.pluginName).app",
                "/Applications/\(config.pluginName)/\(config.pluginName).app"
            ]
            let existingPaths = standalonePaths.filter { fileManager.fileExists(atPath: $0) }
            status += formatFoundPaths(label: "Standalone App", paths: existingPaths)
            for path in existingPaths {
                security += securityBlock(for: path, label: "Standalone App")
                foundAnySecurityInfo = true
            }
            status += "\n"
        }

        if !foundAnySecurityInfo {
            security += "_No installed plug-in bundles found to inspect._\n"
        }

        return (status, security)
    }

    private func scanPluginFormat(label: String, subdirectory: String, extensionName: String) -> (status: String, security: String, found: Bool) {
        let homeDir = fileManager.homeDirectoryForCurrentUser.path
        let paths = [
            "\(homeDir)/Library/Audio/Plug-Ins/\(subdirectory)/\(config.pluginName).\(extensionName)",
            "/Library/Audio/Plug-Ins/\(subdirectory)/\(config.pluginName).\(extensionName)"
        ].filter { fileManager.fileExists(atPath: $0) }

        var status = formatFoundPaths(label: label, paths: paths)
        var security = ""

        for path in paths {
            if let fileInfo = getFileInfo(path) {
                status += fileInfo
            }
            if label == "Audio Unit" {
                status += audioComponentInfo(for: path)
            }
            security += securityBlock(for: path, label: label)
        }

        status += "\n"
        return (status, security, !paths.isEmpty)
    }

    private func formatFoundPaths(label: String, paths: [String]) -> String {
        guard !paths.isEmpty else {
            return "**\(label):** ❌ Not Found\n"
        }

        var output = "**\(label):** ✅ Installed (\(paths.count))\n"
        for path in paths {
            output += "  - Path: `\(path)`\n"
        }
        return output
    }

    private func collectPulpModelState() async -> (summary: String, modelStatePath: String?) {
        let basePath = expandTilde(config.pulpModelPath)
        let modelStatePath = "\(basePath)/model-state.json"
        let modelsPath = "\(basePath)/models"
        var summary = "# Pulp Model State\n\n"
        var foundStatePath: String?

        if fileManager.fileExists(atPath: modelStatePath) {
            foundStatePath = modelStatePath
            summary += "**model-state.json:** Found at `\(modelStatePath)`\n\n"
            if let content = try? String(contentsOfFile: modelStatePath, encoding: .utf8) {
                summary += "```json\n"
                summary += String(content.prefix(4000))
                if content.count > 4000 {
                    summary += "\n... (truncated)"
                }
                summary += "\n```\n\n"
            } else {
                summary += "_Could not read model-state.json_\n\n"
            }
        } else {
            summary += "**model-state.json:** Not found at `\(modelStatePath)`\n\n"
        }

        summary += "## models/ Listing\n\n"
        if let items = try? fileManager.contentsOfDirectory(atPath: modelsPath), !items.isEmpty {
            for item in items.sorted().prefix(100) {
                summary += "- \(item)\n"
            }
            if items.count > 100 {
                summary += "- ... (\(items.count - 100) more)\n"
            }
        } else {
            summary += "_No models directory found or directory is empty at `\(modelsPath)`_\n"
        }

        return (summary, foundStatePath)
    }

    private func collectCrashLogs() async -> (logs: String, paths: [String]) {
        var logs = "# Recent Crash Logs\n\n"
        let crashReportsPath = "\(fileManager.homeDirectoryForCurrentUser.path)/Library/Logs/DiagnosticReports"

        guard let files = try? fileManager.contentsOfDirectory(atPath: crashReportsPath) else {
            return (logs + "_No crash logs found_\n", [])
        }

        let weekAgo = Date().addingTimeInterval(-7 * 24 * 60 * 60)
        let relevantLogs = files.filter { filename in
            filename.contains(config.pluginName) && (filename.hasSuffix(".crash") || filename.hasSuffix(".ips"))
        }.compactMap { filename -> (String, String, Date)? in
            let fullPath = "\(crashReportsPath)/\(filename)"
            guard let attrs = try? fileManager.attributesOfItem(atPath: fullPath),
                  let modDate = attrs[.modificationDate] as? Date,
                  modDate > weekAgo else {
                return nil
            }
            return (filename, fullPath, modDate)
        }.sorted { $0.2 > $1.2 }

        if relevantLogs.isEmpty {
            logs += "_No recent crash logs found for \(config.pluginName)_\n"
            return (logs, [])
        }

        logs += "Found \(relevantLogs.count) crash log(s) from the last 7 days:\n\n"
        let formatter = DateFormatter()
        formatter.dateStyle = .short
        formatter.timeStyle = .short

        for (filename, _, date) in relevantLogs.prefix(5) {
            logs += "- `\(filename)` (\(formatter.string(from: date)))\n"
        }

        if let mostRecent = relevantLogs.first,
           let content = try? String(contentsOfFile: mostRecent.1, encoding: .utf8) {
            logs += "\n## Most Recent Crash\n\n"
            logs += "```\n"
            logs += String(content.prefix(2000))
            if content.count > 2000 {
                logs += "\n... (truncated)\n"
            }
            logs += "```\n"
        }

        return (logs, relevantLogs.prefix(5).map { $0.1 })
    }

    private func runAUValidation() async -> String {
        guard config.checkAU else {
            return "# AU Validation\n\n_Skipped (AU validation not enabled)_\n"
        }

        var validation = "# AU Validation\n\n"
        let result = runProcess(path: "/usr/bin/auval", arguments: ["-v", config.auType, config.auSubtype, config.auManufacturer])

        if result.timedOut {
            validation += "_AU Validation timed out after \(config.diagnosticTimeout) seconds_\n"
        } else if let error = result.error {
            validation += "_Could not run auval: \(error)_\n"
        } else {
            validation += "```\n"
            validation += String(result.output.suffix(1500))
            validation += "\n```\n"
        }

        return validation
    }

    // MARK: - Helper Functions

    private func getSystemProfilerInfo(_ dataType: String, key: String) -> String? {
        let result = runProcess(path: "/usr/sbin/system_profiler", arguments: [dataType, "-json"])
        guard !result.timedOut,
              let data = result.output.data(using: .utf8),
              let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let items = json[dataType] as? [[String: Any]],
              let firstItem = items.first,
              let value = firstItem[key] as? String else {
            return nil
        }

        return value
    }

    private func listAudioDevices() -> String? {
        let result = runProcess(path: "/usr/sbin/system_profiler", arguments: ["SPAudioDataType"])
        guard !result.timedOut, result.error == nil else { return nil }
        return String(result.output.prefix(500))
    }

    private func getFileInfo(_ path: String) -> String? {
        guard let attrs = try? fileManager.attributesOfItem(atPath: path) else {
            return nil
        }

        var info = ""

        if let size = attrs[.size] as? Int64 {
            let formatter = ByteCountFormatter()
            formatter.allowedUnits = [.useKB, .useMB]
            formatter.countStyle = .file
            info += "  - Size: \(formatter.string(fromByteCount: size))\n"
        }

        if let modDate = attrs[.modificationDate] as? Date {
            let formatter = DateFormatter()
            formatter.dateStyle = .medium
            formatter.timeStyle = .short
            info += "  - Modified: \(formatter.string(from: modDate))\n"
        }

        return info
    }

    private func securityBlock(for bundlePath: String, label: String) -> String {
        var block = "## \(label): `\(bundlePath)`\n\n"

        let verify = runProcess(path: "/usr/bin/codesign", arguments: ["--verify", "--deep", "--strict", "--verbose=2", bundlePath])
        block += "### codesign --verify\n\n```\n\(formatProcessResult(verify))\n```\n\n"

        let details = runProcess(path: "/usr/bin/codesign", arguments: ["-dvv", bundlePath])
        block += "### codesign details\n\n```\n\(filterCodesignDetails(details))\n```\n\n"

        let quarantine = runProcess(path: "/usr/bin/xattr", arguments: ["-p", "com.apple.quarantine", bundlePath])
        block += "### quarantine xattr\n\n```\n\(formatProcessResult(quarantine))\n```\n\n"

        if let executablePath = executablePath(forBundleAt: bundlePath) {
            let archs = runProcess(path: "/usr/bin/lipo", arguments: ["-archs", executablePath])
            block += "### executable architectures\n\n"
            block += "Executable: `\(executablePath)`\n\n"
            block += "```\n\(formatProcessResult(archs))\n```\n"
            let output = archs.output
            block += "- arm64: \(output.contains("arm64") ? "✅" : "❌")\n"
            block += "- x86_64: \(output.contains("x86_64") ? "✅" : "❌")\n\n"
        } else {
            block += "### executable architectures\n\n_Could not determine CFBundleExecutable._\n\n"
        }

        block += infoPlistBlock(for: bundlePath)
        return block
    }

    private func filterCodesignDetails(_ result: (output: String, exitCode: Int32, timedOut: Bool, error: String?)) -> String {
        if result.timedOut || result.error != nil {
            return formatProcessResult(result)
        }

        let filtered = result.output.components(separatedBy: .newlines).filter { line in
            line.contains("Authority=") || line.contains("TeamIdentifier=") || line.contains("Identifier=")
        }.joined(separator: "\n")

        return filtered.isEmpty ? result.output : filtered
    }

    private func infoPlistBlock(for bundlePath: String) -> String {
        guard let bundle = Bundle(path: bundlePath), let info = bundle.infoDictionary else {
            return "### Info.plist\n\n_Could not read Info.plist._\n\n"
        }

        var block = "### Info.plist\n\n"
        let bundleId = info["CFBundleIdentifier"] as? String ?? "<missing>"
        let version = info["CFBundleShortVersionString"] as? String ?? "<missing>"
        // Per-format adapters legitimately suffix the base bundle id (e.g.
        // `<base>.au`, `<base>.vst3`, `<base>.clap`), and some formats (CLAP)
        // don't populate CFBundleIdentifier at all. Treat an exact match OR the
        // base-prefixed form as ✅ so the report doesn't cry wolf; only flag a
        // genuinely unrelated id.
        let base = config.pluginBundleId
        let bundleIdOk = !base.isEmpty && (bundleId == base || bundleId.hasPrefix(base + "."))
        let bundleIdMark = bundleId.isEmpty || bundleId == "<missing>"
            ? "ℹ️ not set (normal for some formats)"
            : (bundleIdOk ? "✅" : "⚠️ expected `\(base)` (or `\(base).<format>`)")
        block += "- CFBundleIdentifier: `\(bundleId)` \(bundleIdMark)\n"
        block += "- CFBundleShortVersionString: `\(version)`\n"

        if let components = info["AudioComponents"] as? [[String: Any]], !components.isEmpty {
            block += "- AudioComponents:\n"
            for component in components {
                let type = component["type"] as? String ?? "<missing>"
                let subtype = component["subtype"] as? String ?? "<missing>"
                let manufacturer = component["manufacturer"] as? String ?? "<missing>"
                block += "  - type `\(type)` \(type == config.auType ? "✅" : "⚠️ expected `\(config.auType)`"), subtype `\(subtype)` \(subtype == config.auSubtype ? "✅" : "⚠️ expected `\(config.auSubtype)`"), manufacturer `\(manufacturer)` \(manufacturer == config.auManufacturer ? "✅" : "⚠️ expected `\(config.auManufacturer)`")\n"
            }
        }

        block += "\n"
        return block
    }

    private func audioComponentInfo(for bundlePath: String) -> String {
        guard let bundle = Bundle(path: bundlePath),
              let components = bundle.infoDictionary?["AudioComponents"] as? [[String: Any]],
              !components.isEmpty else {
            return "  - AudioComponents: not found in Info.plist\n"
        }

        var output = "  - AudioComponents:\n"
        for component in components {
            let type = component["type"] as? String ?? "<missing>"
            let subtype = component["subtype"] as? String ?? "<missing>"
            let manufacturer = component["manufacturer"] as? String ?? "<missing>"
            output += "    - type `\(type)`, subtype `\(subtype)`, manufacturer `\(manufacturer)`\n"
        }
        return output
    }

    private func executablePath(forBundleAt bundlePath: String) -> String? {
        guard let bundle = Bundle(path: bundlePath),
              let executableName = bundle.infoDictionary?["CFBundleExecutable"] as? String else {
            return nil
        }

        let macOSPath = "\(bundlePath)/Contents/MacOS/\(executableName)"
        if fileManager.fileExists(atPath: macOSPath) {
            return macOSPath
        }

        let directPath = "\(bundlePath)/\(executableName)"
        if fileManager.fileExists(atPath: directPath) {
            return directPath
        }

        return nil
    }

    private func expandTilde(_ path: String) -> String {
        guard path.hasPrefix("~") else { return path }
        return path.replacingOccurrences(of: "~", with: fileManager.homeDirectoryForCurrentUser.path, options: .anchored)
    }

    private func runProcess(path: String, arguments: [String]) -> (output: String, exitCode: Int32, timedOut: Bool, error: String?) {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: path)
        process.arguments = arguments

        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = pipe

        do {
            try process.run()
        } catch {
            return ("", -1, false, error.localizedDescription)
        }

        let deadline = DispatchTime.now() + .seconds(config.diagnosticTimeout)
        let group = DispatchGroup()
        group.enter()
        DispatchQueue.global(qos: .utility).async {
            process.waitUntilExit()
            group.leave()
        }

        let timedOut = group.wait(timeout: deadline) == .timedOut
        if timedOut {
            process.terminate()
            process.waitUntilExit()
        }

        let data = pipe.fileHandleForReading.readDataToEndOfFile()
        let output = String(data: data, encoding: .utf8) ?? ""
        return (output, process.terminationStatus, timedOut, nil)
    }

    private func formatProcessResult(_ result: (output: String, exitCode: Int32, timedOut: Bool, error: String?)) -> String {
        if result.timedOut {
            return "Timed out after \(config.diagnosticTimeout) seconds\n\(result.output)"
        }
        if let error = result.error {
            return "Failed to run: \(error)"
        }
        let output = result.output.trimmingCharacters(in: .whitespacesAndNewlines)
        return output.isEmpty ? "Exit code: \(result.exitCode)" : "Exit code: \(result.exitCode)\n\(output)"
    }
}
