import Foundation

struct DiagnosticData {
    let findings: [Finding]
    let installSections: [String]
    let attachments: [String: String]
    let files: [String: Data]
    /// Machine-readable summary, written as findings.json next to the report.
    let summaryJSON: Data
    let systemInfo: String
    let pluginStatus: String
    let crashLogs: String
    let auValidation: String
    let userFeedback: String
    let pulpModelState: String
    let securityInfo: String
    let crashFilePaths: [String]
    let pulpModelStatePath: String?
}

/// Strip the local username, home path, and hostname from a diagnostic report
/// so it can be shared without leaking PII. Mirrors the JUCE (Windows/Linux)
/// implementation so both platforms honor ANONYMIZE_USERNAMES / EXCLUDE_USER_PATHS.
/// No-op unless `enabled`.
func anonymizeDiagnosticText(_ text: String, enabled: Bool) -> String {
    guard enabled else { return text }
    var result = text
    let home = FileManager.default.homeDirectoryForCurrentUser.path  // /Users/<name>
    let username = NSUserName()
    if !home.isEmpty { result = result.replacingOccurrences(of: home, with: "/Users/<user>") }
    if !username.isEmpty {
        result = result.replacingOccurrences(of: "/Users/\(username)", with: "/Users/<user>")
        result = result.replacingOccurrences(of: "/\(username)/", with: "/<user>/")
    }
    let hostname = ProcessInfo.processInfo.hostName
    if !hostname.isEmpty { result = result.replacingOccurrences(of: hostname, with: "<hostname>") }
    // Best effort, no promises: the account name also turns up outside paths
    // (reverse-DNS identifiers, log lines), and the user's full name and the
    // computer's name ("Jo's MacBook") can appear in system output. Names
    // shorter than 4 characters are left alone so ordinary words survive.
    var names: [(String, String)] = []
    if username.count >= 4 { names.append((username, "<user>")) }
    let fullName = NSFullUserName()
    if fullName.count >= 4 && fullName != username { names.append((fullName, "<user name>")) }
    if let computer = Host.current().localizedName, computer.count >= 4 { names.append((computer, "<computer name>")) }
    let shortHost = hostname.components(separatedBy: ".").first ?? ""
    if shortHost.count >= 4 { names.append((shortHost, "<hostname>")) }
    for (name, token) in names {
        result = result.replacingOccurrences(of: name, with: token, options: .caseInsensitive)
    }
    return result
}

func renderDiagnosticReport(_ data: DiagnosticData, appName: String, appVersion: String) -> String {
    var body = ""

    body += "# Likely Problems\n\n"
    let ranked = data.findings.sorted { $0.severity < $1.severity }
    if ranked.isEmpty {
        body += "✅ Nothing found that would stop the product from loading.\n"
    } else {
        for finding in ranked {
            body += "- \(finding.severity.mark) \(finding.message)\n"
        }
    }
    body += "\n---\n\n"

    if !data.userFeedback.isEmpty {
        body += "## User Feedback\n\n"
        body += data.userFeedback
        body += "\n\n---\n\n"
    }

    body += data.systemInfo
    body += "\n\n---\n\n"
    for section in data.installSections {
        body += section
        body += "\n\n---\n\n"
    }
    body += data.securityInfo
    body += "\n\n---\n\n"
    if !data.pulpModelState.isEmpty {
        body += data.pulpModelState
        body += "\n\n---\n\n"
    }
    body += data.crashLogs
    body += "\n\n---\n\n"
    body += data.auValidation
    body += "\n\n---\n\n"
    body += "_Report generated by \(appName) v\(appVersion)_\n"

    return body
}

class DiagnosticCollector {
    private let config: AppConfig
    private let fileManager = FileManager.default

    init(config: AppConfig) {
        self.config = config
    }

    func collectDiagnostics(userFeedback: String = "") async -> DiagnosticData {
        let inspector = InstallInspector(config: config) { [self] path, args, timeout in
            runProcess(path: path, arguments: args, timeout: timeout)
        }
        async let systemInfo = collectSystemInfo(inspector: inspector)
        async let plugin = collectPluginStatus()
        async let pulpModel = collectPulpModelState()
        async let crashes = Task.detached { inspector.crashSection() }.value
        let bundles = inspector.installedBundles()
        let componentInstalled = bundles.contains { $0.format == "Audio Unit" }
        async let au = Task.detached { inspector.auRegistrationSection(componentInstalled: componentInstalled) }.value
        async let installer = Task.detached { inspector.installerSection() }.value
        async let gpu = Task.detached { inspector.gpuSection() }.value
        async let systemLog = Task.detached { inspector.unifiedLogSection() }.value
        async let hosts = Task.detached { inspector.hostCachesSection() }.value
        async let daws = Task.detached { inspector.dawSection() }.value
        async let microphone = Task.detached { inspector.microphoneSection() }.value
        async let audio = Task.detached { inspector.audioSection() }.value
        async let displays = Task.detached { inspector.displaysSection() }.value

        let placement = inspector.placementSection(bundles)
        let build = inspector.buildSection(bundles)
        let gatekeeper = inspector.gatekeeperSection(bundles)
        async let logic = Task.detached { inspector.logicSection(bundles) }.value
        async let neighbors = Task.detached { inspector.neighborsSection(bundles) }.value
        async let loadProbe = Task.detached { inspector.loadProbeSection(bundles) }.value
        let workDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("diagnostickit-\(UUID().uuidString)", isDirectory: true)
        async let editorProbe = Task.detached { inspector.editorProbeSection(bundles, workDir: workDir) }.value
        let state = inspector.stateSection()
        let permissions = inspector.permissionsSection(bundles)

        let pluginResult = await plugin
        let crashResult = await crashes
        let pulpModelResult = await pulpModel
        let auResult = await au
        let installerResult = await installer
        let gpuResult = await gpu
        let logResult = await systemLog

        var gpuAndDisplays = gpuResult
        gpuAndDisplays.markdown += "\n" + (await displays).markdown
        let sections = [placement, await logic, await daws, await hosts, await loadProbe, await editorProbe,
                        build, gatekeeper, installerResult, await neighbors, state, permissions,
                        await audio, await microphone, gpuAndDisplays, logResult]
        try? FileManager.default.removeItem(at: workDir)
        var findings = (sections + [crashResult.section, auResult]).flatMap { $0.findings }
        if bundles.isEmpty {
            findings.insert(Finding(severity: .problem, message:
                "\(config.pluginName) is not installed in any standard location on this Mac."), at: 0)
        }
        var attachments: [String: String] = [:]
        var files: [String: Data] = [:]
        for section in sections + [auResult] {
            attachments.merge(section.attachments) { a, _ in a }
            files.merge(section.files) { a, _ in a }
        }
        let summary: [String: Any] = [
            "schema": "diagnostickit.findings.v1",
            "product": config.productName,
            "diagnostics_version": config.appVersion,
            "generated_at": ISO8601DateFormatter().string(from: Date()),
            "macos": ProcessInfo.processInfo.operatingSystemVersionString,
            "architecture": inspector.hostArchitecture(),
            "installed": bundles.map { bundle -> [String: Any] in
                let info = Bundle(path: bundle.path)?.infoDictionary
                return ["format": bundle.format, "path": bundle.path,
                        "version": info?["CFBundleShortVersionString"] as? String ?? "?"]
            },
            "findings": findings.sorted { $0.severity < $1.severity }.map { finding -> [String: String] in
                let level: String
                switch finding.severity {
                case .problem: level = "problem"
                case .warning: level = "warning"
                case .note: level = "note"
                }
                return ["severity": level, "message": finding.message]
            },
        ]
        let summaryJSON = (try? JSONSerialization.data(withJSONObject: summary, options: [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes])) ?? Data()

        return await DiagnosticData(
            findings: findings,
            installSections: sections.map { $0.markdown },
            attachments: attachments,
            files: files,
            summaryJSON: summaryJSON,
            systemInfo: systemInfo,
            pluginStatus: pluginResult.status,
            crashLogs: crashResult.section.markdown,
            auValidation: auResult.markdown,
            userFeedback: userFeedback,
            pulpModelState: pulpModelResult.summary,
            securityInfo: pluginResult.security,
            crashFilePaths: crashResult.paths,
            pulpModelStatePath: pulpModelResult.modelStatePath
        )
    }

    private func collectSystemInfo(inspector: InstallInspector) async -> String {
        var info = "# System Information\n\n"

        let osVersion = ProcessInfo.processInfo.operatingSystemVersionString
        info += "**macOS Version:** \(osVersion)\n"
        info += "**Architecture:** \(inspector.hostArchitecture())\n"
        let rosetta = FileManager.default.fileExists(atPath: "/Library/Apple/usr/share/rosetta/rosetta")
        info += "**Rosetta 2 installed:** \(rosetta ? "yes" : "no")\n"
        info += "**Diagnostics run at:** \(ISO8601DateFormatter().string(from: Date()))\n"

        if let modelName = getSystemProfilerInfo("SPHardwareDataType", key: "Model Name") {
            info += "**Model:** \(modelName)\n"
        }

        if let chipType = getSystemProfilerInfo("SPHardwareDataType", key: "Chip") {
            info += "**Chip:** \(chipType)\n"
        } else if let processorName = getSystemProfilerInfo("SPHardwareDataType", key: "Processor Name") {
            info += "**Processor:** \(processorName)\n"
        }

        if let memory = getSystemProfilerInfo("SPHardwareDataType", key: "Memory") {
            info += "**Memory:** \(memory)\n"
        }


        return info
    }

    private func collectPluginStatus() async -> (status: String, security: String) {
        var status = "# Plugin Status\n\n"
        var security = "# Security Information\n\n"
        var foundAnySecurityInfo = false

        if config.checkAU {
            let result = scanPluginFormat(
                label: "Audio Unit",
                subdirectory: "Components",
                extensionName: "component"
            )
            status += result.status
            security += result.security
            foundAnySecurityInfo = foundAnySecurityInfo || result.found
        }

        if config.checkVST3 {
            let result = scanPluginFormat(
                label: "VST3",
                subdirectory: "VST3",
                extensionName: "vst3"
            )
            status += result.status
            security += result.security
            foundAnySecurityInfo = foundAnySecurityInfo || result.found
        }

        if config.checkCLAP {
            let result = scanPluginFormat(
                label: "CLAP",
                subdirectory: "CLAP",
                extensionName: "clap"
            )
            status += result.status
            security += result.security
            foundAnySecurityInfo = foundAnySecurityInfo || result.found
        }

        if config.checkStandalone {
            let standalonePaths = [
                "/Applications/\(config.pluginName).app",
                "/Applications/\(config.pluginName)/\(config.pluginName).app"
            ]
            let existingPaths = standalonePaths.filter { fileManager.fileExists(atPath: $0) }
            status += formatFoundPaths(label: "Standalone App", paths: existingPaths)
            for path in existingPaths {
                security += securityBlock(for: path, label: "Standalone App")
                foundAnySecurityInfo = true
            }
            status += "\n"
        }

        if !foundAnySecurityInfo {
            security += "_No installed plug-in bundles found to inspect._\n"
        }

        return (status, security)
    }

    private func scanPluginFormat(label: String, subdirectory: String, extensionName: String) -> (status: String, security: String, found: Bool) {
        let homeDir = fileManager.homeDirectoryForCurrentUser.path
        let paths = [
            "\(homeDir)/Library/Audio/Plug-Ins/\(subdirectory)/\(config.pluginName).\(extensionName)",
            "/Library/Audio/Plug-Ins/\(subdirectory)/\(config.pluginName).\(extensionName)"
        ].filter { fileManager.fileExists(atPath: $0) }

        var status = formatFoundPaths(label: label, paths: paths)
        var security = ""

        for path in paths {
            if let fileInfo = getFileInfo(path) {
                status += fileInfo
            }
            if label == "Audio Unit" {
                status += audioComponentInfo(for: path)
            }
            security += securityBlock(for: path, label: label)
        }

        status += "\n"
        return (status, security, !paths.isEmpty)
    }

    private func formatFoundPaths(label: String, paths: [String]) -> String {
        guard !paths.isEmpty else {
            return "**\(label):** ❌ Not Found\n"
        }

        var output = "**\(label):** ✅ Installed (\(paths.count))\n"
        for path in paths {
            output += "  - Path: `\(path)`\n"
        }
        return output
    }

    private func collectPulpModelState() async -> (summary: String, modelStatePath: String?) {
        // Only model-backed products configure a model path; for the rest the
        // section would report an irrelevant absence.
        guard !config.pulpModelPath.isEmpty else { return ("", nil) }
        let basePath = expandTilde(config.pulpModelPath)
        let modelStatePath = "\(basePath)/model-state.json"
        let modelsPath = "\(basePath)/models"
        var summary = "# Pulp Model State\n\n"
        var foundStatePath: String?

        if fileManager.fileExists(atPath: modelStatePath) {
            foundStatePath = modelStatePath
            summary += "**model-state.json:** Found at `\(modelStatePath)`\n\n"
            if let content = try? String(contentsOfFile: modelStatePath, encoding: .utf8) {
                summary += "```json\n"
                summary += String(content.prefix(4000))
                if content.count > 4000 {
                    summary += "\n... (truncated)"
                }
                summary += "\n```\n\n"
            } else {
                summary += "_Could not read model-state.json_\n\n"
            }
        } else {
            summary += "**model-state.json:** Not found at `\(modelStatePath)`\n\n"
        }

        summary += "## models/ Listing\n\n"
        if let items = try? fileManager.contentsOfDirectory(atPath: modelsPath), !items.isEmpty {
            for item in items.sorted().prefix(100) {
                summary += "- \(item)\n"
            }
            if items.count > 100 {
                summary += "- ... (\(items.count - 100) more)\n"
            }
        } else {
            summary += "_No models directory found or directory is empty at `\(modelsPath)`_\n"
        }

        return (summary, foundStatePath)
    }

    // MARK: - Helper Functions

    private func getSystemProfilerInfo(_ dataType: String, key: String) -> String? {
        let result = runProcess(path: "/usr/sbin/system_profiler", arguments: [dataType, "-json"])
        guard !result.timedOut,
              let data = result.output.data(using: .utf8),
              let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let items = json[dataType] as? [[String: Any]],
              let firstItem = items.first,
              let value = firstItem[key] as? String else {
            return nil
        }

        return value
    }

    private func getFileInfo(_ path: String) -> String? {
        guard let attrs = try? fileManager.attributesOfItem(atPath: path) else {
            return nil
        }

        var info = ""

        if let size = attrs[.size] as? Int64 {
            let formatter = ByteCountFormatter()
            formatter.allowedUnits = [.useKB, .useMB]
            formatter.countStyle = .file
            info += "  - Size: \(formatter.string(fromByteCount: size))\n"
        }

        if let modDate = attrs[.modificationDate] as? Date {
            let formatter = DateFormatter()
            formatter.dateStyle = .medium
            formatter.timeStyle = .short
            info += "  - Modified: \(formatter.string(from: modDate))\n"
        }

        return info
    }

    private func securityBlock(for bundlePath: String, label: String) -> String {
        var block = "## \(label): `\(bundlePath)`\n\n"

        let verify = runProcess(path: "/usr/bin/codesign", arguments: ["--verify", "--deep", "--strict", "--verbose=2", bundlePath])
        block += "### codesign --verify\n\n```\n\(formatProcessResult(verify))\n```\n\n"

        let details = runProcess(path: "/usr/bin/codesign", arguments: ["-dvv", bundlePath])
        block += "### codesign details\n\n```\n\(filterCodesignDetails(details))\n```\n\n"

        let quarantine = runProcess(path: "/usr/bin/xattr", arguments: ["-p", "com.apple.quarantine", bundlePath])
        block += "### quarantine xattr\n\n```\n\(formatProcessResult(quarantine))\n```\n\n"

        if let executablePath = executablePath(forBundleAt: bundlePath) {
            let archs = runProcess(path: "/usr/bin/lipo", arguments: ["-archs", executablePath])
            block += "### executable architectures\n\n"
            block += "Executable: `\(executablePath)`\n\n"
            block += "```\n\(formatProcessResult(archs))\n```\n"
            let output = archs.output
            block += "- arm64: \(output.contains("arm64") ? "✅" : "❌")\n"
            block += "- x86_64: \(output.contains("x86_64") ? "✅" : "❌")\n\n"
        } else {
            block += "### executable architectures\n\n_Could not determine CFBundleExecutable._\n\n"
        }

        block += infoPlistBlock(for: bundlePath)
        return block
    }

    private func filterCodesignDetails(_ result: (output: String, exitCode: Int32, timedOut: Bool, error: String?)) -> String {
        if result.timedOut || result.error != nil {
            return formatProcessResult(result)
        }

        let filtered = result.output.components(separatedBy: .newlines).filter { line in
            line.contains("Authority=") || line.contains("TeamIdentifier=") || line.contains("Identifier=")
        }.joined(separator: "\n")

        return filtered.isEmpty ? result.output : filtered
    }

    private func infoPlistBlock(for bundlePath: String) -> String {
        guard let bundle = Bundle(path: bundlePath), let info = bundle.infoDictionary else {
            return "### Info.plist\n\n_Could not read Info.plist._\n\n"
        }

        var block = "### Info.plist\n\n"
        let bundleId = info["CFBundleIdentifier"] as? String ?? "<missing>"
        let version = info["CFBundleShortVersionString"] as? String ?? "<missing>"
        // Per-format adapters legitimately suffix the base bundle id (e.g.
        // `<base>.au`, `<base>.vst3`, `<base>.clap`), and some formats (CLAP)
        // don't populate CFBundleIdentifier at all. Treat an exact match OR the
        // base-prefixed form as ✅ so the report doesn't cry wolf; only flag a
        // genuinely unrelated id.
        let base = config.pluginBundleId
        let bundleIdOk = !base.isEmpty && (bundleId == base || bundleId.hasPrefix(base + "."))
        let bundleIdMark = bundleId.isEmpty || bundleId == "<missing>"
            ? "ℹ️ not set (normal for some formats)"
            : (bundleIdOk ? "✅" : "⚠️ expected `\(base)` (or `\(base).<format>`)")
        block += "- CFBundleIdentifier: `\(bundleId)` \(bundleIdMark)\n"
        block += "- CFBundleShortVersionString: `\(version)`\n"

        if let components = info["AudioComponents"] as? [[String: Any]], !components.isEmpty {
            block += "- AudioComponents:\n"
            for component in components {
                let type = component["type"] as? String ?? "<missing>"
                let subtype = component["subtype"] as? String ?? "<missing>"
                let manufacturer = component["manufacturer"] as? String ?? "<missing>"
                block += "  - type `\(type)` \(type == config.auType ? "✅" : "⚠️ expected `\(config.auType)`"), subtype `\(subtype)` \(subtype == config.auSubtype ? "✅" : "⚠️ expected `\(config.auSubtype)`"), manufacturer `\(manufacturer)` \(manufacturer == config.auManufacturer ? "✅" : "⚠️ expected `\(config.auManufacturer)`")\n"
            }
        }

        block += "\n"
        return block
    }

    private func audioComponentInfo(for bundlePath: String) -> String {
        guard let bundle = Bundle(path: bundlePath),
              let components = bundle.infoDictionary?["AudioComponents"] as? [[String: Any]],
              !components.isEmpty else {
            return "  - AudioComponents: not found in Info.plist\n"
        }

        var output = "  - AudioComponents:\n"
        for component in components {
            let type = component["type"] as? String ?? "<missing>"
            let subtype = component["subtype"] as? String ?? "<missing>"
            let manufacturer = component["manufacturer"] as? String ?? "<missing>"
            output += "    - type `\(type)`, subtype `\(subtype)`, manufacturer `\(manufacturer)`\n"
        }
        return output
    }

    private func executablePath(forBundleAt bundlePath: String) -> String? {
        guard let bundle = Bundle(path: bundlePath),
              let executableName = bundle.infoDictionary?["CFBundleExecutable"] as? String else {
            return nil
        }

        let macOSPath = "\(bundlePath)/Contents/MacOS/\(executableName)"
        if fileManager.fileExists(atPath: macOSPath) {
            return macOSPath
        }

        let directPath = "\(bundlePath)/\(executableName)"
        if fileManager.fileExists(atPath: directPath) {
            return directPath
        }

        return nil
    }

    private func expandTilde(_ path: String) -> String {
        guard path.hasPrefix("~") else { return path }
        return path.replacingOccurrences(of: "~", with: fileManager.homeDirectoryForCurrentUser.path, options: .anchored)
    }

    func runProcess(path: String, arguments: [String], timeout: Int? = nil) -> (output: String, exitCode: Int32, timedOut: Bool, error: String?) {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: path)
        process.arguments = arguments

        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = pipe

        do {
            try process.run()
        } catch {
            return ("", -1, false, error.localizedDescription)
        }

        // Drain the pipe while the process runs: a child that writes more than
        // the pipe buffer (auval, log show) would otherwise block forever.
        var collected = Data()
        let readQueue = DispatchQueue(label: "diagnostickit.pipe")
        let readGroup = DispatchGroup()
        readGroup.enter()
        readQueue.async {
            collected = pipe.fileHandleForReading.readDataToEndOfFile()
            readGroup.leave()
        }

        let deadline = DispatchTime.now() + .seconds(timeout ?? config.diagnosticTimeout)
        let group = DispatchGroup()
        group.enter()
        DispatchQueue.global(qos: .utility).async {
            process.waitUntilExit()
            group.leave()
        }

        let timedOut = group.wait(timeout: deadline) == .timedOut
        if timedOut {
            process.terminate()
            process.waitUntilExit()
        }

        readGroup.wait()
        let output = String(decoding: collected, as: UTF8.self)
        // A child killed by a signal reports the signal number as its status;
        // negate it so a crash can never read as an ordinary exit code.
        let status = process.terminationReason == .uncaughtSignal ? -process.terminationStatus : process.terminationStatus
        return (output, status, timedOut, nil)
    }

    private func formatProcessResult(_ result: (output: String, exitCode: Int32, timedOut: Bool, error: String?)) -> String {
        if result.timedOut {
            return "Timed out after \(config.diagnosticTimeout) seconds\n\(result.output)"
        }
        if let error = result.error {
            return "Failed to run: \(error)"
        }
        let output = result.output.trimmingCharacters(in: .whitespacesAndNewlines)
        return output.isEmpty ? "Exit code: \(result.exitCode)" : "Exit code: \(result.exitCode)\n\(output)"
    }
}
